name: weekly fetch and parse GPU info to API

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '00 00 * * 1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build 🔧
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas requests lxml

      - name: Update data
        run: |
          python update.py

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gpu-data
          force: true
